<!-- Etiquette avec fiche client -->
        <article style="border: solid 1px #000; padding:10px;">
            <p><?= $tplVars['User']['LastName']; ?> <?= $tplVars['User']['FirstName']; ?></p>
            <p><?= $tplVars['User']['Address']; ?></p>
            <p><?= $tplVars['User']['ZipCode']; ?></p>
            <p><?= $tplVars['User']['City']; ?></p>
        </article>
        <h3>Bon de commande n° <?= $tplVars['Order']; ?></h3>
        <!-- Le bon de commande -->
        <table class="table table-bordered table-striped">
            <thead class="thead-dark">
                <th>Produit</th>
                <th class="text-right">Prix unitaire</th>
                <th class="text-center">Quantité</th>
                <th class="text-right">Total eco tax (inclus)</th>
                <th class="text-right">Prix total</th>
            </thead>
            <tbody>
                <!-- début de boucle -->
                <?php 
                $total = 0;
                $total_eco = 0;
                foreach($tplVars['OrderDetails'] as $item): 
                    
                $total += number_format($item['Total'],2,".", "");
                $total_eco += number_format($item['Total_eco'],2,".","");
                ?>
                <tr>
                    <td><?= htmlspecialchars($item['Name']);?></td>
                    <td class="text-right"><?= number_format($item['MSRP'],2);?> €</td>
                    <td class="text-center"><?= intval($item['Quantity']);?></td>
                    <td class="text-right"><?= number_format($item['Total_eco'],2);?> €</td>
                    <td class="text-right"><?= number_format($item['Total'],2);?> €</td>
                </tr>
                <?php endforeach; ?>
                <!-- fin de boucle -->
            </tbody>
            <tfoot>
                <tr>
                    <th colspan="4" class="text-right">TVA</th>
                    <th class="text-right"><?= number_format($total * TVA,2);?> €</th>
                </tr>
                <tr>
                    <th colspan="4" class="text-right">Montant Total TTC</th>
                    <th class="text-right"><?= $total;?> €</th>
                </tr>
                <tr>
                    <th colspan="4" class="text-right">Eco tax (inclus)</th>
                    <th class="text-right"><?= $total_eco;?>  €</th>
                </tr>
            </tfoot>
        </table>
        <form method="POST" action="<?= $tplVars['WWW_URL']; ?>index.php?controller=cart&task=step2">
            <input type="hidden" name="order" value="<?= $tplVars['Token']; ?>" />
            <button class="button" type="submit">Payer la commande</button>
        </form>