<form enctype="multipart/form-data" action="<?= $tplVars['WWW_URL']; ?>index.php?controller=Admin\<?= $tplVars['crud'];?>&task=create" method="POST">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center my-4">
        <a class="btn btn-outline-secondary" href="<?= $tplVars['WWW_URL']; ?>index.php?controller=Admin\<?= $tplVars['crud'];?>&task=index"><i class="fa fa-times"></i> Annuler les modifications</a>
        <button class="btn btn-primary"><i class="fa fa-check"></i> Valider et enregistrer</button>
    </div>


    <fieldset class="p-3 bg-light">
        <legend>Gestion</legend>
        <div class="form-group row">
            <div class="col-form-label col-sm-3 pt-0">Statut</div>
            <div class="col-sm-9">
                <div class="form-check">
                    <input class="form-check-input" type="radio" id="product_status_draft" name="product_status" value="1" checked>
                    <label class="form-check-label text-muted" for="product_status_draft">En attente de mise en ligne</label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" id="product_status_ok" name="product_status" value="2">
                    <label class="form-check-label text-success" for="product_status_ok">En boutique</label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" id="product_status_off" name="product_status" value="3">
                    <label class="form-check-label text-danger" for="product_status_off">Retiré</label>
                </div>
            </div>
        </div>
        <div class="form-group row">
            <label for="shelf" class="col-sm-3 col-form-label">Rayon</label>
            <div class="col-sm-9">
                <select class="form-control" id="shelf" name="shelf">
								<option value="0">Choisir un rayon ...</option>
								<!-- boucler sur les rayons -->
								<?php
								foreach($tplVars['productlines'] as $item):
								?>
								<option value="<?= intval($item['Id']);?>"><?= htmlspecialchars($item['Name']);?></option>
							    <?php
							    endforeach;
							    ?>
							</select>
            </div>
        </div>
    </fieldset>
    <fieldset class="p-3 bg-light">
        <legend>Présentation</legend>
        <div class="form-group row">
            <label for="product_brand" class="col-sm-3 col-form-label">Marque</label>
            <div class="col-sm-9">
                <select class="form-control" id="product_brand" name="product_brand">
						<option value="0">Choisir une marque ...</option>
						<?php
						foreach($tplVars['brands'] as $item):
						?>
						<option value="<?= intval($item['Id']);?>"><?= htmlspecialchars($item['Name']);?></option>
					    <?php
					    endforeach;
					    ?>
                </select>
            </div>
        </div>
        <div class="form-group row">
            <label for="product_ref" class="col-sm-3 col-form-label">Nom du produit</label>
            <div class="col-sm-9">
                <input type="text" class="form-control" id="product_ref" name="product_ref" value="">
            </div>
        </div>
        <div class="form-group row">
            <label for="product_photo_1" class="col-sm-3 col-form-label">Visuel principal</label>
            <div class="col-sm-9">
                <div class="custom-file">
                    <input type="file" class="custom-file-input" id="product_visuel" name="product_visuel">
                    <label class="custom-file-label" for="product_visuel" data-browse="Parcourir">Choisir un fichier</label>
                </div>
            </div>
        </div>
        <div class="form-group row">
            <label for="product_tags" class="col-sm-3 col-form-label">Etiquettes</label>
            <select class="form-control" id="product_tags" name="product_tags[]" multiple>
						<?php
						foreach($tplVars['tags'] as $item):
						?>
						<option value="<?= intval($item['Id']);?>"><?= htmlspecialchars($item['Name']);?></option>
					    <?php
					    endforeach;
					    ?>
						
                </select>
            
        </div>
        <div class="form-group row">
            <label for="product_price" class="col-sm-3 col-form-label">Prix</label>
            <div class="col-sm-9">
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text">Prix d'achat</span>
                    </div>
                    <input type="number" class="form-control" id="product_buyprice" name="product_buyprice" value="">
                    <div class="input-group-append">
                        <span class="input-group-text">€</span>
                    </div>
                    <div class="input-group-prepend">
                        <span class="input-group-text">Prix de vente</span>
                    </div>
                    <input type="number" class="form-control" id="product_msrp" name="product_msrp" value="">
                    <div class="input-group-append">
                        <span class="input-group-text">€</span>
                    </div>
                    <div class="input-group-prepend">
                        <span class="input-group-text">éco-participation</span>
                    </div>
                    <input type="number" class="form-control" name="product_price_eco" value="">
                    <div class="input-group-append">
                        <span class="input-group-text">€</span>
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group row">
            <label for="product_stock" class="col-sm-3 col-form-label">Stock du produit</label>
            <div class="col-sm-9">
                <input type="number" class="form-control" id="product_stock" name="product_stock" value="">
            </div>
        </div>
        <div class="form-group row">
            <label for="product_desc_0" class="col-sm-3 col-form-label">Description principale</label>
            <div class="col-sm-9">
                <textarea class="form-control" id="product_desc_0" name="product_desc_0" rows="20"></textarea>
            </div>
        </div>
    </fieldset>
</form>
