<form action="<?= $tplVars['WWW_URL']; ?>index.php?controller=Admin\<?= $tplVars['crud'];?>&task=update" method="POST">
    <input type="hidden" name="id" value="<?= intval($_GET['id']); ?>" />
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center my-4">
        <a class="btn btn-outline-secondary" href="<?= $tplVars['WWW_URL']; ?>index.php?controller=Admin\<?= $tplVars['crud'];?>&task=index"><i class="fa fa-times"></i> Annuler les modifications</a>
        <button class="btn btn-primary"><i class="fa fa-check"></i> Valider et enregistrer</button>
    </div>

    <fieldset class="p-3 bg-light">
        <div class="form-group row">
            <label for="status" class="col-sm-3 col-form-label">Statut</label>
            <div class="col-sm-9">
                <select class="form-control" id="status" name="status">
					<option value="1"<?php echo (intval($tplVars['Order']['Status']) == 1) ? ' selected' : '';?>>Commande non payée</option>
					<option value="2"<?php echo (intval($tplVars['Order']['Status']) == 2) ? ' selected' : '';?>>Commande payée</option>
					<option value="3"<?php echo (intval($tplVars['Order']['Status']) == 3) ? ' selected' : '';?>>Commande expédiée</option>
				</select>
				</div>
        </div>
    </fieldset>
</form>
<h3>Bon de commande n° <?= intval($_GET['id']); ?></h3>
<!-- detail de la commande -->
<!-- Etiquette avec fiche client -->
        <article style="border: solid 1px #000; padding:10px;">
            <p><?= $tplVars['User']['LastName']; ?> <?= $tplVars['User']['FirstName']; ?></p>
            <p><?= $tplVars['User']['Address']; ?></p>
            <p><?= $tplVars['User']['ZipCode']; ?></p>
            <p><?= $tplVars['User']['City']; ?></p>
        </article>
        <hr>
        <!-- Le bon de commande -->
        <table class="table table-bordered table-striped">
			<thead class="thead-dark">
                <th>Produit</th>
                <th class="text-right">Prix unitaire</th>
                <th class="text-center">Quantité</th>
                <th class="text-right">Total eco tax (inclus)</th>
                <th class="text-right">Prix total</th>
            </thead>
            <tbody>
                <!-- début de boucle -->
                <?php 
                $total = 0;
                $total_eco = 0;
                foreach($tplVars['OrderDetails'] as $item): 
                    
                $total += number_format($item['Total'],2,".", "");
                $total_eco += number_format($item['Total_eco'],2,".","");
                ?>
                <tr>
                    <td><?= htmlspecialchars($item['Name']);?></td>
                    <td class="text-right"><?= number_format($item['MSRP'],2);?> €</td>
                    <td class="text-center"><?= intval($item['Quantity']);?></td>
                    <td class="text-right"><?= number_format($item['Total_eco'],2);?> €</td>
                    <td class="text-right"><?= number_format($item['Total'],2);?> €</td>
                </tr>
                <?php endforeach; ?>
                <!-- fin de boucle -->
            </tbody>
            <tfoot>
                <tr>
                    <th colspan="4" class="text-right">TVA</th>
                    <th class="text-right"><?= number_format($total * TVA,2);?> €</th>
                </tr>
                <tr>
                    <th colspan="4" class="text-right">Montant Total TTC</th>
                    <th class="text-right"><?= $total;?> €</th>
                </tr>
                <tr>
                    <th colspan="4" class="text-right">Eco tax (inclus)</th>
                    <th class="text-right"><?= $total_eco;?>  €</th>
                </tr>
            </tfoot>
        </table>
